### ISSUE TITLE
 Invalid parameter value on Sysctl

### ISSUE THREAD

**Issue by rmacian** [thias/puppet-sysctl#16]
Hi,

I'm running into problems with hiera,  From the documentation i guessed I have to set on my node a definition like this:

class { 'sysctl::base': hiera_merge_values => true,}

and then in hiera I set (sorry , tabulation is not showing fine)

sysctl::base::values:
  net.core.netdev_max_backlog:
    value: '30000'
  net.core.somaxconn:
    value: '1024'
  net.ipv4.tcp_max_syn_backlog:
    value: '4096'

The catalog does not compile with pupppet agent but it still works with puppet apply.

Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter value on Sysctl[net.core.netdev_max_backlog] on node myserver
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

**Comment by deviantony** [comment]
Same problem here using Puppet 3.7.3 !

**Comment by pavelsmolka** [comment]
It seems more several other people encountered the same problem recently. Is there a chance to either include this for next major release (2.0) or at least to find some middle ground? I have updated my pull request #17 so it's ready to be merged back to upstream/master.

**Comment by split3** [comment]
I'm seeing the same issue, any update on when this will be fixed?

**Comment by thias** [comment]
I'd be interested in knowing if this is still happening, and finding a fix that does not involved changing the main `sysctl` definition into a class, as that would cause major breakage.

**Comment by rndmh3ro** [comment]
I'm still having the problem:
```
Error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter value on Sysctl[vm.swappiness] on node host
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run
```
With variable:
```
vm.swappiness:
  value: 0
```

Version: thias-sysctl (v1.0.6)

**Comment by thaylin** [comment]
I am having the same issue, it is intermittent and happens with different variables.

**Comment by agomerz** [comment]
Same issue here not using Heira,
```
Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter value on Sysctl[net.core.rmem_max] at
```
```
sysctl {'net.core.rmem_max':        value => '16777216' }
```
Does not occur with puppet agent -t but with regular agent runs intermittently.
Puppet 3.7.4

**Comment by rekcah78** [comment]
if i rename the module with an other name, 
it works fine, i think now puppet have native sysctl function

**Comment by kilianw** [comment]
Same issue here:

error: Could not retrieve catalog from remote server: Error 400 on SERVER: Invalid parameter prefix on Sysctl[kernel.shmmax]

sysctl { 'kernel.shmmax': prefix => '60', value => '2147483648' }

**Comment by nshobe** [comment]
I'm seeing this issue as well, and it's being brought up by a dependency from elastic/elasticsearch. Will likely end up needing to fork that module just to run it because of this bug.
